spring:
  application:
    name: customer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:2017/customer_db
    username: bank_customer
    password: bank@168
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
server:
  port: 8081
