spring:
  application:
    name: account
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:2016/account_db
    username: bank_account
    password: bank@168
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080